BATCH_SIZE = 64 
DATASET_MEAN = [0.733, 0.734, 0.735] 
DATASET_VAR = [0.1652,0.1654, 0.1658] 
TRAIN_SCALE_MIN = 1.0 
TRAIN_SCALE_MAX = 1.0
USE_BFLOAT16 = True 
OUTPUT_SIZE = 640 
HEIGHT = 480 
WIDTH = 640
PARALLEL_CALLS = 64

TPU_ZONE = 'us-central1-f'
GCP_PROJECT = 'tpus-230912'
TPU = 'node-1'
USE_TPU=True
MODE = 'train-and-eval'

DATA_DIR = 'gs://tpu-buckets/tf-records'
TRAIN_DIR = DATA_DIR + '/train*'
VAL_DIR = DATA_DIR + '/val*'
EXPORT_DIR = 'gs://tpu-buckets/export_dir'
MODEL_DIR = 'gs://tpu-buckets/model_dir'

RESNET_DEPTH = 101
PRECISION='bfloat16'
SKIP_HOST_CALL = False

NUM_TRAIN_IMAGES = 34200
NUM_VAL_IMAGES = 3800
EPOCHS = 30

TRAIN_STEPS = (NUM_TRAIN_IMAGES * EPOCHS) // BATCH_SIZE
STEPS_PER_EVAL = (NUM_TRAIN_IMAGES) // BATCH_SIZE
ITERS_PER_LOOP = STEPS_PER_EVAL
DATA_FORMAT = 'channels_last'
TRANSPOSE_INPUT=True
NUM_CORES = 8

BASE_LR=0.1
MOMENTUM=0.9
WEIGHT_DECAY=1e-4
POLY_RATE=0.0
