BATCH_SIZE = 64
DATASET_MEAN = [0, 0, 0]
DATASET_VAR = [1, 1, 1]
TRAIN_SCALE_MIN = 0.8
TRAIN_SCALE_MAX = 1.2
USE_BFLOAT16 = True
OUTPUT_SIZE = 224 #
PARALLEL_CALLS = 64

TPU_URL
GCP_PROJECT
TPU_ZONE
MODEL_DIR
NUM_CORES=8
NUM_CORE_PER_REPLICA=8
INPUT_PAR_DIMS=[1, 4, 2, 1]
EVAL_BATCH_SIZE=1
EVAL_SAMPLES=5000
ITERS_PER_LOOP = 100
TRAINING_FILES = 
VALIDATION_FILES = 
UM_EXAMPLES_PER_EPOCH = 15000
NUM_EPOCHS = 15
MODE = 'train'

